# .goreleaser.yml
# Corrected for the v2 schema.
version: 2

# The 'builds' block is a top-level key.
builds:
  - id: "burstgridgo"
    main: ./cmd/cli/
    binary: burstgridgo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildDate={{.Date}}

# 'dockers' is also a top-level key.
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/specialistvlad/burstgridgo:{{ .Tag }}"
      - "ghcr.io/specialistvlad/burstgridgo:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=A declarative, concurrency-first load testing tool."
      - "--label=org.opencontainers.image.url=https://github.com/specialistvlad/burstgridgo"
      - "--label=org.opencontainers.image.source=https://github.com/specialistvlad/burstgridgo"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

# The 'release' block remains a top-level key.
release:
  name_template: "Release {{.Version}}"
  prerelease: auto

# The 'checksum' block remains a top-level key.
checksum:
  name_template: "checksums.txt"

# The 'snapshot' block remains a top-level key.
snapshot:
  name_template: "{{ incpatch .Version }}-next-{{ .ShortCommit }}"

# The 'changelog' block remains a top-level key.
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "merge conflict"
